### PR TITLE
Prepare for adding tests of generated code in new files

### PR DESCRIPTION
**Pull request by jnm2**
Separated out from https://github.com/YairHalberstadt/stronginject/pull/143 in order to keep the diff smaller.

### CODE REVIEW

**Comment by jnm2** [comment]
Looks like I broke Ubuntu and Windows builds, hopefully for the same reason.

**Comment by YairHalberstadt** [comment]
Are you ok with fixing the tests, or do you want any help there?

**Comment by jnm2** [comment]
@YairHalberstadt I figured out the Ubuntu error. I'm not sure how anything in this pull requests causes the loads of copies of this error:

> CSC : error CS8032: An instance of analyzer Microsoft.CodeAnalysis.MakeFieldReadonly.MakeFieldReadonlyDiagnosticAnalyzer cannot be created from C:\Users\runneradmin\AppData\Local\Microsoft\dotnet\sdk\5.0.400\Sdks\Microsoft.NET.Sdk\codestyle\cs\Microsoft.CodeAnalysis.CodeStyle.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=3.11.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.

Can you check whether a new build of the main branch succeeds?

**Comment by YairHalberstadt** [comment]
Looks like windows is failing on main too.

**Comment by YairHalberstadt** [comment]
Fixed at https://github.com/YairHalberstadt/stronginject/pull/146

The windows images keep on causing problems each time github updates them. I'm now just using dotnet instead of msbuild so that shouldn't be an issue from  now on.

**Comment by YairHalberstadt** [comment]
You'll have to pull main

**Pull request merged**
